### ISSUE TITLE
Add logging if there is an error in getLocation

### ISSUE THREAD

**Issue by davist11** [lukeyouell/craft3-geocookie#4]
I think we might be hitting our max daily API limit for ipapi.co, but since there is no logging, I can't know for sure without hacking the plugin directly on production. It would be really useful to log when there is some sort of error retrieving the location.

If you don't think you have time to add this anytime soon, let me know, and I can submit a PR.

**Comment by lukeyouell** [comment]
@davist11 added and released! 🙂

Just search your logs for `geocookie`
