### ISSUE TITLE
Error with ipapi.co

### ISSUE THREAD

**Issue by davist11** [lukeyouell/craft3-geocookie#6]
We are using this plugin and ipapi.co with a paid plan. Somewhat recently, we've been getting cURL timeout errors, but only when using ipapi.co as the API Source.

```
cURL error 28: Connection timed out after 5073 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

If I switch to a different API source, things work fine. I was going to maybe contact ipapi.co directly, but their API status shows no issues, and I can curl it directly from the command line and it works fine.

Any thoughts?

**Comment by lukeyouell** [comment]
@davist11 it looks like the endpoint was incorrectly set to `ipapi.com` in the last update, when it should be `ipapi.co`

It has been rectified in the latest release. My apologies!

**Comment by davist11** [comment]
Haha dang I should have noticed that. Silly TLDs. Thanks!
