### ISSUE TITLE
FR: Add Cloudflare Capability

### ISSUE THREAD

**Issue by mariovass** [lukeyouell/craft3-geocookie#8]
Inspiration: https://github.com/madebymutual/Country-Detect

Docs: https://api.cloudflare.com/#zone-settings-get-ip-geolocation-setting

**Comment by lukeyouell** [comment]
@mariovass we discussed this on the Craft Slack, but I'll post the answer here for anyone it might help.

Craft 3 allows you to fetch the headers via Twig, so you can achieve this using the following:

```twig
{% set country = craft.app.request.headers.get('CF-IPCountry') %}
```
